<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class MedicamentSeeder extends Seeder
{
    public function run()
    {
        $medicaments = [
            'ABAISSE LANGUE',
            'ACTRAPIDE',
            'ACUPAN',
            'ADRENALINE',
            'AIGUILLE A INSULINE',
            'AIGUILLE PL',
            'ALCOOL',
            'AMOXICILLINE',
            'ARTEMETHER 20MG',
            'ARTEMETHER 80MG',
            'ARTESUN 120MG',
            'ARTESUN 30MG',
            'ARTESUN 60MG',
            'ATROPINE',
            'CURAM',
            'BACPERAZONE',
            'BANDE N°10',
            'BANDE N°15',
            'BANDE N°5',
            'BANDE N°7',
            'BANDELETTE A GLYCEMIE',
            'BETADINE GYNECO',
            'BETADINE JAUNE',
            'BETADINE ROUGE',
            'BIPLATRIX N°02',
            'BIPLATRIX N°10',
            'BIPLATRIX N°15',
            'BIPLATRIX N°20',
            'BRASSA',
            'CANULE DE GUEDELL',
            'CEFOTAXIME',
            'CEFTRIAXONE',
            'CHLE DE CALCIUM',
            'CHLE DE POTASSIUM',
            'CHLE DE SODIUM',
            'CLAMP DE BARR',
            'COMPRESSE NON STERIL',
            'COMPRESSE STERIL',
            'COTON',
            'COUCHE ALDUTE',
            'CUTICELLE',
            'DAKIN GRAND',
            'DAKIN PETIT',
            'DETAIL GANT',
            'DETAIL SPARADRAP',
            'DEXAMETAXONE',
            'DICLOFENAC',
            'DISLEP CP',
            'DISLEP INJ',
            'DRAIN',
            'DYCINONE INJ',
            'EAU OXYGENE GRAND',
            'EAU OXYGENE PETIT',
            'ECHAPE COURDE AU CPS',
            'ECHAPE DIMMOBILISATION',
            'ELECTRODE',
            'EPHEDRINE',
            'EPICRANIEN BLEU',
            'EPICRANIEN ORANGE',
            'GASPRAL',
            'ETHER',
            'EXACYL',
            'FENTANYL',
            'FIL NYLON N°0',
            'FIL NYLON N°01',
            'FIL NYLON N°2',
            'FIL NYLON N°2/0',
            'FIL NYLON N°3/0',
            'G10',
            'GANT STERIL L',
            'GANT STERIL N°7/5',
            'GANT STERIL N°8',
            'GANT STERIL N°M',
            'GANT STERIL N°XL',
            'GAUZE SPONGE N°05',
            'GELOPLASMAT',
            'GENTA COLLYRE',
            'GENTAMYCINE',
            'GLUCOSE',
            'GREEN TEA',
            'HALODERM',
            'HALOTANE',
            'HB- PLUS',
            'HEMAFER INJ',
            'HPV',
            'HYDROFERA BLUE',
            'I-GEL',
            'IMOBILISATION GENOU',
            'INTIM- T',
            'INTRANULE BLEU',
            'INTRANULE GRISE',
            'INTRANULE JAUNE',
            'INTRANULE ROSE',
            'INTRANULE VERT',
            'KETAMINE',
            'KIT CESARIENNE',
            'LAME BISTORIE N°23',
            'LAROSCORBINE',
            'LAROXYL',
            'LASILIX',
            'LOVENOX 4000 UN',
            'LOVENOX 6000 UN',
            'LOXEN',
            'LOXEN - CP',
            'LUNETTE A OXYGENE',
            'MAGNESIUM',
            'MARCAÏNE',
            'METRO PERF',
            'MIDAZOLAM',
            'MORFIN',
            'MUKESTAT-150',
            'MYOXERIL',
            'NOVALGIN',
            'NOVO MIX',
            'NOVO RAPIDE',
            'OFLOXACINE PERF',
            'OPTILOCK',
            'PANSEMENT TRANSPARENT',
            'PERFALGAN',
            'PERFUSEUR',
            'POCHE STOMIE',
            'POCHE URINAIRE',
            'POT A URINE',
            'PROKEFFEN',
            'QUININE',
            'RHENA',
            'RINGER',
            'ROBINER',
            'S N G N° 06',
            'S N G N° 12',
            'S N G N° 18',
            'S N G N°08',
            'S N G N°10',
            'S N G N°14',
            'S N G N°16',
            'S.N.G N°22',
            'SALE (SSI)',
            'SANG 0-',
            'SANG 0+',
            'SANG A-',
            'SANG A+',
            'SANG AB-',
            'SANG AB+',
            'SANG B-',
            'SANG B+',
            'SERINGUE 10CC',
            'SERINGUE 20CC',
            'SERINGUE 2CC',
            'SERINGUE 50CC',
            'SERINGUE 5CC',
            'SERINGUE 60 CC',
            'SERINGUE BT LONG N°10C',
            'SERINGUE INSULINE',
            'SERVIETTE',
            'SOFBAND N°10',
            'SOFBAND N°15',
            'SOFBAND N°5',
            'SONDE ASPIRATION N°14',
            'SONDE ASPIRATION N°18',
            'SONDE ASPIRATION N°22',
            'SONDE ASPIRATION N°8',
            'SONDE INTUBATION N°12',
            'SONDE INTUBATION N°16',
            'SONDE INTUBATION N°18',
            'SONDE INTUBATION N°8',
            'SONDE URINAIRE N°08',
            'SONDE URINAIRE N°10',
            'SONDE URINAIRE N°12',
            'SONDE URINAIRE N°14',
            'SONDE URINAIRE N°16',
            'SONDE URINAIRE N°18',
            'SONDE URINAIRE N°19',
            'SONDE URINAIRE N°20',
            'SONDE URINAIRE N°22',
            'SPARADRAP CURAD',
            'SPASFON INJ',
            'SUPRAGEL',
            'SYNTHOCINONE',
            'TENSOPLAST 15CM',
            'TENSOPLAST 20CM',
            'TENSOPLAST 6 CM',
            'TETANOS',
            'TEXT DE GROSSESSE 1000',
            'THERMOMETRE',
            'THIOPENAL',
            'TRABAR',
            'TRANSFUSEUR',
            'TRIAM-DENK',
            'TROCARD',
            'VALIUM',
            'VICRYL N°1',
            'VICRYL N°2',
            'VICRYL N°2/0',
            'VICRYL N°3/0',
            'VICRYL N°4/0',
            'VICRYL N°5/0',
            'VITAMINE C',
            'VITAMINE K1',
            'VOGALENE',
            'XYLOCAÏNE 2 %',
            'XYLOCAÏNE 50ML',
            'XYLOCAÏNE GEL',
            'TUBE ROUGE',
            'TUBE VIOLET',
            'TUBE BLEU',
            'TUBE GRIS',
            'CIMETIDINE',
            'COMPRESSE 40*40',
            'COMPRESSE A GAZ',
            'TEXTE DE GROSSESSE LISETTE',
            'VICRYL 0',
            'LUNETTE A OXYGENE BB',
            'SALE 1000',
            'SONDE ASPIRATION BB',
            'ENDOPROST',
            'BIPLATRIX 15X3',
            'BIPLATRIX 15X2',
            'VIT B12',
            'CASAQUE JETTABLE',
            'VENTONINE',
            'LUNETTE A OXYGENE PREDIA',
            'MASSE A OXYGENE BB',
            'MASSE A OXYGENE ALDUTE',
            'CELESEINE',
            '9 VIT',
            'SODROL',
            'HYDROCORTISONE',
            'SONDE A 2 VOIE',
            'SONDE A 3 VOIE',
            'NYL0N 1/0',
            'KETESSE',
            'DICACILLINE',
            'LARGATIL',
            'BANDE 30 CM',
            'IMIPENEN 500MG',
            'SALE 250',
            'GLUCOSE 250',
            'NOVALGIN 500',
            'FINE ECHO',
            'GLUCOSE 30',
            'PROPOFOL/DUPRIVAN',
            'JERSEY',
            'HALDOL',
            'BAZATHINE'
        ];

        foreach ($medicaments as $medicament) {
            DB::table('medicaments')->insert([
                'code' => $this->generateUniqueCode($medicament),
                'nom' => $medicament,
                'unite_mesure' => 'unité', // Valeur par défaut, à adapter selon le médicament
                'prix_achat' => 0.00, // Valeur par défaut, à modifier selon les besoins
                'prix_vente' => 0.00, // Valeur par défaut, à modifier selon les besoins
                'stock' => 0,
                'stock_alerte' => 10,
                'date_peremption' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }

    private function generateUniqueCode($nom)
    {
        // Générer un code unique basé sur le nom
        $prefix = strtoupper(substr(preg_replace('/[^a-zA-Z]/', '', $nom), 0, 3));
        $random = strtoupper(Str::random(3));
        $code = $prefix . '-' . $random;
        
        // Vérifier si le code existe déjà
        while (DB::table('medicaments')->where('code', $code)->exists()) {
            $random = strtoupper(Str::random(3));
            $code = $prefix . '-' . $random;
        }
        
        return $code;
    }
}